"use strict";
function main() {
  let $t0, $t1, $t2, $t3, $t4;
  let x = {v: 10};
  let p = {v: ({a: x, i: "v"} ? {a: ({a: x, i: "v"}).a, i: ({a: x, i: "v"}).i} : null)};
  p.v.a[p.v.i] = 20;
  (console.log((x.v)));
  (console.log((p.v.a[p.v.i])));
  let a = [1, 2, 3, 4];
  let q = {a: a, i: 0};
  (console.log((q.a[q.i])));
  q.i++;
  (console.log((q.a[q.i])));
  q.i += (2);
  (console.log((q.a[q.i])));
  (console.log((((q ? q.i : 0) - (({a: a, i: 0}) ? (({a: a, i: 0})).i : 0)))));
  (console.log((($t0 = ({a: (({a: a, i: 0}) ? (({a: a, i: 0})).a : null), i: (({a: a, i: 0}) ? (({a: a, i: 0})).i : 0) + (2)}), $t0.a[$t0.i]))));
  (console.log(((((q ? q.i : 0) > (({a: a, i: 0}) ? (({a: a, i: 0})).i : 0)) ? 1 : 0))));
  (console.log(((($t2 = ($t1 = ({a: (({a: a, i: 0}) ? (({a: a, i: 0})).a : null), i: (({a: a, i: 0}) ? (({a: a, i: 0})).i : 0) + (3)}), $t1), (q === $t2 || (q && $t2 && q.a === $t2.a && q.i === $t2.i))) ? 1 : 0))));
  let n = null;
  (console.log((((n === null) ? 1 : 0))));
  (console.log((((p.v === null) ? 1 : 0))));
  let h = (($t3 = {a: [99], i: 0}, $t3) ? {a: (($t3 = {a: [99], i: 0}, $t3)).a, i: (($t3 = {a: [99], i: 0}, $t3)).i} : null);
  (console.log((h.a[h.i])));
  let arr = (($t4 = {a: new Array(3).fill(0), i: 0}, $t4) ? {a: (($t4 = {a: new Array(3).fill(0), i: 0}, $t4)).a, i: (($t4 = {a: new Array(3).fill(0), i: 0}, $t4)).i} : null);
  arr.a[arr.i] = 7;
  arr.a[arr.i + (2)] = 9;
  (console.log((((arr.a[arr.i] + arr.a[arr.i + (1)]) + arr.a[arr.i + (2)]))));
  let pp = ({a: p, i: "v"} ? {a: ({a: p, i: "v"}).a, i: ({a: p, i: "v"}).i} : null);
  (pp.a[pp.i]).a[(pp.a[pp.i]).i] = 30;
  (console.log((x.v)));
  return 0;
}
main();
